/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package tn.nebulagaming;

import static com.codename1.ui.CN.*;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.io.Log;
import com.codename1.ui.Toolbar;
import tn.nebulagaming.gui.Login1;
import tn.nebulagaming.utils.ShoppingCartManager;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename
 * One</a> for the purpose of building native mobile applications using Java.
 */
public class MyApplication {

    private Form current;
    private Resources theme;

    public void init(Object context) {
	// use two network threads instead of one
	updateNetworkThreadCount(2);

	theme = UIManager.initFirstTheme("/theme");

	// Enable Toolbar on all Forms by default
	Toolbar.setGlobalToolbar(true);

	// Pro only feature
	Log.bindCrashProtection(true);

	addNetworkErrorListener(err -> {
	    // prevent the event from propagating
	    err.consume();
	    if (err.getError() != null) {
		Log.e(err.getError());
	    }
	    Log.sendLogAsync();
	    Dialog.show("Connection Error", "There was a networking error in the connection to " + err.getConnectionRequest().getUrl(), "OK", null);
	});
    }

    public void start() {

        
	if (current != null) {
	    current.show();
	    return;
	}
		ShoppingCartManager.getInstance();
		new Login1(theme).show();
    }

    public void stop() {
	current = getCurrentForm();
	if (current instanceof Dialog) {
	    ((Dialog) current).dispose();
	    current = getCurrentForm();
	}
    }

    public void destroy() {
    }

}